#include <iostream>
#include <vector>
#include <string>
#include <unordered_map>

std::unordered_map<int, std::vector<std::string>> trainRoutes;

void addTrainRoute(int routeNumber, const std::vector<std::string>& routeStations) {
    trainRoutes[routeNumber] = routeStations;
}

void getRoute(int routeNumber) {
    if (trainRoutes.find(routeNumber) != trainRoutes.end()) {
        std::vector<std::string> routeStations = trainRoutes[routeNumber];
        std::cout << "Route for train number " << routeNumber << " is: " << std::endl;
        for (const auto& station : routeStations) {
            std::cout << station << std::endl;
        }
    } else {
        std::cout << "Route for train number " << routeNumber << " not found." << std::endl;
    }
}

int main() {
    // Example usage:
    addTrainRoute(20978, {"DELHI CANTT", "GURGAON", "REWARI", "ALWAR", "JAIPUR", "AJMER JN"});
    addTrainRoute(22436, {"VARANASI JN", "PRAYAGRAJ JN", "KANPUR CENTRAL", "NEW DELHI"});
    addTrainRoute(22435, {"RAMANATHAPURAM", "PARAMAKKUDI", "MANAMADURAI JN", "KARAIKKUDI JN", "TIRUCHCHIRAPALI", "THANJAVUR", "KUMBAKONAM", "MAYILADUTURAI J", "SIRKAZHI", "CHIDAMBARAM", "CUDDALORE PORT", "VILLUPURAM JN", "CHENGALPATTU", "CHENNAI EGMORE", "GUDUR JN", "NELLORE", "ONGOLE", "TENALI JN", "VIJAYAWADA JN", "WARANGAL", "RAMGUNDAM", "SIRPUR KAGAZNGR", "BALHARSHAH", "CHANDRAPUR", "SEVAGRAM", "NAGPUR", "ITARSI JN", "JABALPUR", "KATNI", "SATNA", "PRAYAGRAJ JN", "GYANPUR ROAD", "BANARAS"});
    addTrainRoute(22439, {"NEW DELHI", "AMBALA CANT JN", "LUDHIANA JN", "JAMMU TAWI", "MATA VAISHNO DEVI KAT"});
    addTrainRoute(22440, {"MATA VAISHNO DEVI KATRA", "JAMMU TAWI", "LUDHIANA JN", "AMBALA CANT JN", "NEW DELHI"});
    addTrainRoute(20901, {"MUMBAI CENTRAL", "BORIVALI", "VAPI", "SURAT", "VADODARA JN", "AHMEDABAD JN", "GANDHINAGAR CAP"});
    addTrainRoute(22902, {"GANDHINAGAR CAP", "AHMEDABAD JN", "VADODARA JN", "SURAT", "VAPI", "BORIVALI", "MUMBAI CENTRAL"});
    addTrainRoute(22447, {"NEW DELHI", "AMBALA CANT JN", "CHANDIGARH", "ANANDPUR SAHIB", "UNA HIMACHAL", "AMBANDAURA"});
    addTrainRoute(22448, {"AMBANDAURA", "UNA HIMACHAL", "ANANDPUR SAHIB", "CHANDIGARH", "AMBALA CANT JN", "NEW DELHI"});
    addTrainRoute(20607, {"CHENNAI CENTRAL", "KATPADI JN", "KSR BANGALORE CY JN", "MYSORE JN"});
    addTrainRoute(20608, {"CHENNAI CENTRAL", "KATPADI JN", "KSR BANGALORE CY JN", "MYSORE JN"});
    addTrainRoute(20826, {"NAGPUR", "GONDIA JN", "RAJ NANDGAON", "DURG", "RAIPUR JN", "BILASPUR JN"});
    addTrainRoute(20825, {"BILASPUR JN", "RAIPUR JN", "DURG", "RAJ NANDGAON", "GONDIA JN", "NAGPUR"});
    addTrainRoute(22301, {"HOWRAH JN", "BOLPUR S NIKTN", "MALDA TOWN", "BARSOI JN", "NEW JALPAIGURI"});
    addTrainRoute(22302, {"NEW JALPAIGURI", "BARSOI JN", "MALDA TOWN", "BOLPUR S NIKTN", "HOWRAH JN"});
    addTrainRoute(20833, {"VISHAKAPATNAM", "SAMALKOT JN", "RAJAMUNDRY", "VIJAYAWADA JN", "KHAMMAM", "WARANGAL", "SECUNDERABAD JN"});
    addTrainRoute(20834, {"SECUNDERABAD JN", "WARANGAL", "KHAMMAM", "VIJAYAWADA JN", "RAJAMUNDRY", "SAMALKOT JN", "VISHAKAPATNAM"});
    addTrainRoute(22225, {"C SHIVAJI TERM MUMBAI", "DADAR", "THANE", "KALYAN JN", "PUNE JN", "KURDUVADI", "SOLAPUR JN"});
    addTrainRoute(22226, {"SOLAPUR JN", "KURDUVADI", "PUNE JN", "KALYAN JN", "THANE", "DADAR", "C SHIVAJI TERM MUMBAI"});
    addTrainRoute(22224, {"SAINAGAR SHIRDI", "NASIK ROAD", "KALYAN JN", "THANE"});
    addTrainRoute(22223, {"C SHIVAJI TERM MUMBAI", "DADAR", "THANE", "KALYAN JN", "NASIK ROAD", "SAINAGAR SHIRDI"});
    addTrainRoute(20171, {"RANI KAMLAPATI", "V LAKSHMIBAI JHANSI", "GWALIOR", "AGRA CANTT", "H NIZAMUDDIN"});
    addTrainRoute(20172, {"H NIZAMUDDIN", "AGRA CANTT", "GWALIOR", "V LAKSHMIBAI JHANSI", "RANI KAMLAPATI"});

    // New route
    addTrainRoute(20702, {"TIRUPATI", "NELLORE", "ONGOLE", "GUNTUR JN", "NALGONDA", "SECUNDERABAD JN"});

    addTrainRoute(20701, {"SECUNDERABAD JN", "NALGONDA", "GUNTUR JN", "ONGOLE", "NELLORE", "TIRUPATI"});

    addTrainRoute(20643, {"CHENNAI CENTRAL", "SALEM JN", "ERODE JN", "TIRUPPUR", "COIMBATORE JN"});
    addTrainRoute(20644, {"COIMBATORE JN", "TIRUPPUR", "ERODE JN", "SALEM JN", "CHENNAI CENTRAL"});

    addTrainRoute(22227, {"NEW JALPAIGURI", "NEW COOCH BEHAR", "NEW ALIPURDAUR", "KOKRAJHAR", "NEW BONGAIGAON", "KAMAKHYA", "GUWAHATI"});

    addTrainRoute(22228, {"GUWAHATI", "KAMAKHYA", "NEW BONGAIGAON", "KOKRAJHAR", "NEW ALIPURDAUR", "NEW COOCH BEHAR", "NEW JALPAIGURI"});

    addTrainRoute(20977, {"AJMER JN", "JAIPUR", "ALWAR", "REWARI", "GURGAON", "DELHI CANTT"});

    addTrainRoute(20633, {"KASARAGOD", "KANNUR", "KOZHIKODE", "SHORANUR JN", "THRISUR", "ERNALKULAM TOWN", "KOTTAYAM", "KOLLAM JN", "TRIVANDRUM CNTL"});

    addTrainRoute(22895, {"HOWRAH JN", "KHARAGPUR JN", "BALASORE", "BHADRAKH", "JAJPUR K ROAD", "CUTTACK", "BHUBANESWAR", "KHURDA ROAD JN", "PURI"});

    addTrainRoute(22896, {"PURI", "KHURDA ROAD JN", "BHUBANESWAR", "CUTTACK", "JAJPUR K ROAD", "BHADRAKH", "BALASORE", "KHARAGPUR JN", "HOWRAH JN"});

    addTrainRoute(22458, {"DEHRADUN", "HARIDWAR JN", "ROORKEE", "SAHARANPUR", "DEOBAND", "MUZAFFARNAGAR", "MEERUT CITY", "ANAND VIHAR TRM"});
    
    addTrainRoute(22457, {"ANAND VIHAR TRM", "MEERUT CITY", "MUZAFFARNAGAR", "DEOBAND", "SAHARANPUR", "ROORKEE", "HARIDWAR JN", "DEHRADUN"});
    
    addTrainRoute(20911, {"INDORE JN BG", "UJJAIN JN", "BHOPAL JN", "ITARSI JN", "BETUL", "NAGPUR"});

addTrainRoute(22350, {"RANCHI", "BARKA KANA", "HAZARIBAGH TOWN", "KODERMA", "GAYA JN", "PATNA JN"});
addTrainRoute(22349, {"PATNA JN", "GAYA JN", "KODERMA", "HAZARIBAGH TOWN", "BARKA KANA", "RANCHI"});
addTrainRoute(22230, {"MADGAON", "THIVIM", "KANKAVALI", "RATNAGIRI", "KHED", "PANVEL", "THANE", "DADAR", "C SHIVAJI TERM MUMBAI"});
addTrainRoute(20925, {"AHMEDABAD JN", "SABARMATI JN", "SANAND", "VIRAMGAM JN", "SURENDRANAGAR JN", "WANKANER JN", "RAJKOT JN", "JAMNAGAR"});
addTrainRoute(20926, {"JAMNAGAR", "RAJKOT JN", "WANKANER JN", "SURENDRANAGAR JN", "VIRAMGAM JN", "SANAND", "SABARMATI JN", "AHMEDABAD JN"});
addTrainRoute(20898, {"RANCHI", "MURI", "KOTSHILA", "PURULIA JN", "CHANDIL JN", "TATANAGAR JN", "KHARAGPUR JN", "HOWRAH JN"});
addTrainRoute(20980, {"JAIPUR", "KISHANGARH", "AJMER JN", "BIJAINAGAR", "BHILWARA", "CHITTAURGARH", "MAVLI JN", "RANAPRATAPNAGAR", "UDAIPUR CITY"});
addTrainRoute(20897, {"HOWRAH JN", "KHARAGPUR JN", "TATANAGAR JN", "CHANDIL JN", "PURULIA JN", "KOTSHILA", "MURI", "RANCHI"});
addTrainRoute(20979, {"UDAIPUR CITY", "RANAPRATAPNAGAR", "MAVLI JN", "CHITTAURGARH", "BHILWARA", "BIJAINAGAR", "AJMER JN", "KISHANGARH", "JAIPUR"});
addTrainRoute(20678, {"VIJAYAWADA JN", "TENALI JN", "ONGOLE", "NELLORE", "RENIGUNTA JN", "CHENNAI CENTRAL"});
addTrainRoute(20677, {"CHENNAI CENTRAL", "RENIGUNTA JN", "NELLORE", "ONGOLE", "TENALI JN", "VIJAYAWADA JN"});
addTrainRoute(20632, {"TRIVANDRUM CNTL", "KOLLAM JN", "ALLEPPEY", "ERNAKULAM JN", "THRISUR", "SHORANUR JN", "TIRUR", "KOZHIKODE", "KANNUR", "KASARAGOD"});
addTrainRoute(20631, {"KASARAGOD", "KANNUR", "KOZHIKODE", "TIRUR", "SHORANUR JN", "THRISUR", "ERNAKULAM JN", "ALLEPPEY", "KOLLAM JN", "TRIVANDRUM CNTL"});
addTrainRoute(20704, {"YESVANTPUR JN", "DHARMAVARAM JN", "ANANTAPUR", "KURNOOL TOWN", "MAHBUBNAGAR", "KACHEGUDA"});
addTrainRoute(20703, {"KACHEGUDA", "MAHBUBNAGAR", "KURNOOL TOWN", "ANANTAPUR", "DHARMAVARAM JN", "YESVANTPUR JN"});
addTrainRoute(20665, {"CHENNAI EGMORE", "TAMBARAM", "VILLUPURAM JN", "TIRUCHCHIRAPALI", "DINDIGUL JN", "MADURAI JN", "VIRUDUNAGAR JN", "TIRUNELVELI JN"});
addTrainRoute(20666, {"TIRUNELVELI JN", "VIRUDUNAGAR JN", "MADURAI JN", "DINDIGUL JN", "TIRUCHCHIRAPALI", "VILLUPURAM JN", "TAMBARAM", "CHENNAI EGMORE"});
addTrainRoute(20835, {"ROURKELA", "JHARSUGUDA JN", "SAMBALPUR CITY", "RAIRAKHOL", "ANGUL", "TALCHER ROAD", "DHENKANAL", "CUTTACK", "BHUBANESWAR", "KHURDA ROAD JN", "PURI"});
addTrainRoute(20836, {"PURI", "KHURDA ROAD JN", "BHUBANESWAR", "CUTTACK", "DHENKANAL", "TALCHER ROAD", "ANGUL", "RAIRAKHOL", "SAMBALPUR CITY", "JHARSUGUDA JN", "ROURKELA"});
addTrainRoute(22347, {"HOWRAH JN", "DURGAPUR", "ASANSOL JN", "JAMTARA", "JASIDIH JN", "LUCKEESARAI JN", "MOKAMEH JN", "PATNA SAHEB", "PATNA JN"});
addTrainRoute(22348, {"PATNA JN", "PATNA SAHEB", "MOKAMEH JN", "LUCKEESARAI JN", "JASIDIH JN", "JAMTARA", "ASANSOL JN", "DURGAPUR", "HOWRAH JN"});
addTrainRoute(22549, {"GORAKHPUR JN", "BASTI", "AYODHYA", "LUCKNOW NR"});
addTrainRoute(22550, {"LUCKNOW NR", "AYODHYA", "BASTI", "GORAKHPUR JN"});
addTrainRoute(12462, {"SABARMATI JN", "MAHESANA JN", "PALANPUR JN", "ABU ROAD", "FALNA", "PALI MARWAR", "JODHPUR JN"});
addTrainRoute(12461, {"JODHPUR JN", "PALI MARWAR", "FALNA", "ABU ROAD", "PALANPUR JN", "MAHESANA JN", "SABARMATI JN"});
addTrainRoute(07305, {"SECUNDERABAD JN", "JANGAON", "KAZIPET JN", "PEDDAPALLI", "RAMGUNDAM", "BELAMPALLI", "SIRPUR KAGAZNGR", "BALHARSHAH", "NAGPUR", "ITARSI JN", "PIPARIYA", "JABALPUR", "KATNI", "SATNA", "MANIKPUR JN", "PRAYAGRAJ CHHEOKI", "BANARAS"});
addTrainRoute(20173, {"RANI KAMLAPATI", "NARMADAPURAM", "ITARSI JN", "PIPARIYA", "NARSINGHPUR", "JABALPUR", "KATNI", "MAIHAR", "SATNA", "REWA"});
addTrainRoute(20174, {"REWA", "SATNA", "MAIHAR", "KATNI", "JABALPUR", "NARSINGHPUR", "PIPARIYA", "ITARSI JN", "NARMADAPURAM", "RANI KAMLAPATI"});
addTrainRoute(20662, {"DHARWAR", "HUBBALLI JN", "DAVANGERE", "YESVANTPUR JN", "KSR BANGALORE CY JN"});
addTrainRoute(20661, {"KSR BANGALORE CY JN", "YESVANTPUR JN", "DAVANGERE", "HUBBALLI JN", "DHARWAR"});
addTrainRoute(20912, {"NAGPUR", "BETUL", "ITARSI JN", "BHOPAL JN", "UJJAIN JN", "INDORE JN BG"});
addTrainRoute(22229, {"C SHIVAJI TERM MUMBAI", "DADAR", "THANE", "PANVEL", "KHED", "RATNAGIRI", "KANKAVALI", "THIVIM", "MADGAON"});





    int inputRouteNumber;
    std::cout << "Enter a route number: ";
    std::cin >> inputRouteNumber;

    getRoute(inputRouteNumber);

    return 0;
}
